### PR TITLE
Yingtong Peng and Xiaoran Hu

### PR DESCRIPTION
**Pull request by XiaoranHu**
Yingtong Peng and Xiaoran Hu Community Contribution

### CODE REVIEW

**Comment by YingtongPeng** [comment]
Animation_Graphs

**Comment by Howard-HaoChang** [comment]
Please do not include capital letters in your file name.

**Comment by XiaoranHu** [comment]
Hi Howard,
  Do we need to pull a new request? We do not know how to change the name
of the Rmd on GitHub. Thank you so much!!
Best,
Xiaoran

Howard-HaoChang ***@***.***>于2022年4月4日 周一下午3:06写道：

**Comment by XiaoranHu** [comment]
Hi Howard,
  We have changed the name to lower letter.
Thanks,
Xiaoran

Xiaoran Hu ***@***.***>于2022年4月4日 周一下午3:25写道：

**Comment by Howard-HaoChang** [comment]
Thanks

**Comment by Howard-HaoChang** [comment]
Thank you for your contribution! 🎉

**Pull request merged**
