### PR TITLE
basic_visualization_cheatsheet

### PR DESCRIPTION
**Pull request by ym2856**

### CODE REVIEW

**Comment by ym2856** [comment]
This file contain basic quick reference for data visualization in rstudio.

**Comment by JErinLiu** [comment]
Please change your numbered subheadings to hashtags. Example:  1.Histogram -> # Histogram

please see 3.4 Optional tweaks part 2 for more instructions.
https://jtr13.github.io/cc22spring/github-submission-instructions.html

**Comment by ym2856** [comment]
Hello,
I'm sorry just seeing this. I have already made the changes but why it does
not show up on Github?

Best,
Yue

JErinLiu ***@***.***> 于2022年4月13日周三 18:47写道：

**Comment by JErinLiu** [comment]
Thanks for your contribution! 🎉 Now we have merged your pull request and you can see your part on GitHub.

**Pull request merged**
