### PR TITLE
Tmap cheatsheet group4

### PR DESCRIPTION
**Pull request by yfsherry**
Group 4 contribution: spatial data visualization package `tmap` cheatsheet. (First commit)

### CODE REVIEW

**Comment by jtr13** [comment]
Perfect timing as I will be talking a bit about `tmap` today in class. I actually looked for a cheatsheet and couldn't find one so this will be very useful!

**Comment by jtr13** [comment]
Thank you for your contribution! 🎉

**Comment by yfsherry** [comment]
Dear professor,

Thank you for your email, professor!
I will complete the Community Contribution submission as soon as possible.

Best regards
Yuxuan Fu

**Comment by yfsherry** [comment]
Dear Professor Robbins,

I am so glad that our tmap cheatsheet can help you. We would like to add a
little bit more information for you, which may give you more useful
information. Would you mind us resubmit an updated cheat sheet in the
coursework and the GitHub?
Thank you and we're looking forward to your reply.

best,

**Comment by jtr13** [comment]
Sure, that would be great! I also would encourage you to share it with the tmap package authors. I happen to be looking for a tmap cheatsheet yesterday and came across this: https://github.com/r-tmap/tmap/issues/447  You could respond to that issue and attach a copy of the pdf.

**Pull request merged**
